#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-selenium
Version  : 2.52.0
Release  : 2
URL      : https://github.com/SeleniumHQ/selenium/archive/selenium-2.52.0.tar.gz
Source0  : https://github.com/SeleniumHQ/selenium/archive/selenium-2.52.0.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-api/2.52.0/selenium-api-2.52.0.jar
Source2  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-api/2.52.0/selenium-api-2.52.0.pom
Source3  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-chrome-driver/2.52.0/selenium-chrome-driver-2.52.0.jar
Source4  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-chrome-driver/2.52.0/selenium-chrome-driver-2.52.0.pom
Source5  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-edge-driver/2.52.0/selenium-edge-driver-2.52.0.jar
Source6  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-edge-driver/2.52.0/selenium-edge-driver-2.52.0.pom
Source7  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-firefox-driver/2.52.0/selenium-firefox-driver-2.52.0.jar
Source8  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-firefox-driver/2.52.0/selenium-firefox-driver-2.52.0.pom
Source9  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-htmlunit-driver/2.52.0/selenium-htmlunit-driver-2.52.0.jar
Source10  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-htmlunit-driver/2.52.0/selenium-htmlunit-driver-2.52.0.pom
Source11  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-ie-driver/2.52.0/selenium-ie-driver-2.52.0.jar
Source12  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-ie-driver/2.52.0/selenium-ie-driver-2.52.0.pom
Source13  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-java/2.52.0/selenium-java-2.52.0.jar
Source14  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-java/2.52.0/selenium-java-2.52.0.pom
Source15  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-leg-rc/2.52.0/selenium-leg-rc-2.52.0.jar
Source16  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-leg-rc/2.52.0/selenium-leg-rc-2.52.0.pom
Source17  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-parent/2.52.0/selenium-parent-2.52.0.pom
Source18  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-remote-driver/2.52.0/selenium-remote-driver-2.52.0.jar
Source19  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-remote-driver/2.52.0/selenium-remote-driver-2.52.0.pom
Source20  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-safari-driver/2.52.0/selenium-safari-driver-2.52.0.jar
Source21  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-safari-driver/2.52.0/selenium-safari-driver-2.52.0.pom
Source22  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-support/2.52.0/selenium-support-2.52.0.jar
Source23  : https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-support/2.52.0/selenium-support-2.52.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : AFL-2.1 Apache-2.0 GPL-2.0 MIT MS-PL
Requires: mvn-selenium-data = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
A pure-JavaScript CSS selector engine designed to be easily dropped in to a host library.

%package data
Summary: data components for the mvn-selenium package.
Group: Data

%description data
data components for the mvn-selenium package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-api/2.52.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-api/2.52.0/selenium-api-2.52.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-api/2.52.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-api/2.52.0/selenium-api-2.52.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/2.52.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/2.52.0/selenium-chrome-driver-2.52.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/2.52.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/2.52.0/selenium-chrome-driver-2.52.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/2.52.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/2.52.0/selenium-edge-driver-2.52.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/2.52.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/2.52.0/selenium-edge-driver-2.52.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/2.52.0
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/2.52.0/selenium-firefox-driver-2.52.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/2.52.0
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/2.52.0/selenium-firefox-driver-2.52.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-htmlunit-driver/2.52.0
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-htmlunit-driver/2.52.0/selenium-htmlunit-driver-2.52.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-htmlunit-driver/2.52.0
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-htmlunit-driver/2.52.0/selenium-htmlunit-driver-2.52.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/2.52.0
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/2.52.0/selenium-ie-driver-2.52.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/2.52.0
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/2.52.0/selenium-ie-driver-2.52.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-java/2.52.0
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-java/2.52.0/selenium-java-2.52.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-java/2.52.0
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-java/2.52.0/selenium-java-2.52.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-leg-rc/2.52.0
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-leg-rc/2.52.0/selenium-leg-rc-2.52.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-leg-rc/2.52.0
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-leg-rc/2.52.0/selenium-leg-rc-2.52.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-parent/2.52.0
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-parent/2.52.0/selenium-parent-2.52.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/2.52.0
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/2.52.0/selenium-remote-driver-2.52.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/2.52.0
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/2.52.0/selenium-remote-driver-2.52.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/2.52.0
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/2.52.0/selenium-safari-driver-2.52.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/2.52.0
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/2.52.0/selenium-safari-driver-2.52.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-support/2.52.0
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-support/2.52.0/selenium-support-2.52.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-support/2.52.0
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-support/2.52.0/selenium-support-2.52.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-api/2.52.0/selenium-api-2.52.0.jar
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-api/2.52.0/selenium-api-2.52.0.pom
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/2.52.0/selenium-chrome-driver-2.52.0.jar
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/2.52.0/selenium-chrome-driver-2.52.0.pom
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/2.52.0/selenium-edge-driver-2.52.0.jar
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/2.52.0/selenium-edge-driver-2.52.0.pom
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/2.52.0/selenium-firefox-driver-2.52.0.jar
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/2.52.0/selenium-firefox-driver-2.52.0.pom
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-htmlunit-driver/2.52.0/selenium-htmlunit-driver-2.52.0.jar
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-htmlunit-driver/2.52.0/selenium-htmlunit-driver-2.52.0.pom
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/2.52.0/selenium-ie-driver-2.52.0.jar
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/2.52.0/selenium-ie-driver-2.52.0.pom
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-java/2.52.0/selenium-java-2.52.0.jar
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-java/2.52.0/selenium-java-2.52.0.pom
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-leg-rc/2.52.0/selenium-leg-rc-2.52.0.jar
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-leg-rc/2.52.0/selenium-leg-rc-2.52.0.pom
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-parent/2.52.0/selenium-parent-2.52.0.pom
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/2.52.0/selenium-remote-driver-2.52.0.jar
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/2.52.0/selenium-remote-driver-2.52.0.pom
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/2.52.0/selenium-safari-driver-2.52.0.jar
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/2.52.0/selenium-safari-driver-2.52.0.pom
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-support/2.52.0/selenium-support-2.52.0.jar
/usr/share/java/.m2/repository/org/seleniumhq/selenium/selenium-support/2.52.0/selenium-support-2.52.0.pom
